package game;

/***
 * 
 * @author Andrew Connell
 *
 * The Entity class creates a base template
 * for any object that can exist on a Board.
 * 
 * Each entity will have a BoardPosition array
 * [which will ensure the board is able to handle entities]
 *
 */

public class Entity {
    
    /* Each entity has an ID number generated by the game */
    protected int id_; 
    
    /* Each Entity belongs to a Board [owner_] */
    protected Board owner_;
    
    /* Every Entity has a name */
    protected String name_;
    
    /* Whether the Entity is lodged at this position or can move */
    protected Boolean lodged_;
    
    /* 
     * The positions_ array provides details of where on the 
     * board this entity exists.
     */ 
    protected BoardPosition[] positions_;
    
    
    /** REDUNDANT DEFAULT IMPLICIT CONSTRUCTOR: DO NOT USE **/
    public Entity() {
        // Redundant
    }
    
    
    /** Constructor for N number of positions **/
    public Entity(int numberOfPositions, Board onBoard) {
        
        /* Set the board this entity is on */
        owner_ = onBoard;

        /* Set this entity's id_ */
        setEntityID();
        
        /* Default set name to "Entity" */
        name_ = "Entity";
        
        /* Create array for positions and null the values */
        positions_ = new BoardPosition[numberOfPositions];

        setDefaultPos(positions_);
        
    }

    
    /** Methods for Entity follow... **/
    
    /* 
     * Default the positions_ to null.
     */
    private void setDefaultPos(BoardPosition[] setNull) {
        
        for (int x = 0; x < setNull.length; x++) {
            positions_[x] = new BoardPosition(-1, -1);
        }
        
    }
    
    
    /*
     * Get the name of the Entity
     */
    public String getName() {
        
        return name_;
        
    }
    
    
    /*
     * Set the ID for this Entity 
     */
    public void setEntityID() {
     
        id_ = owner_.getNextIDNumber();
    
    }
    
    
    /* 
     * Get the ID for this Entity
     */
    public int getEntityID() {
    
        return id_;
        
    }
    
    
    /*
     * Check if entity is lodged
     */
    public Boolean entityLodgeCheck() {
        
        return lodged_;
        
    }
    
}
